src/device_manager/views/main.py
#!/usr/bin/env/ python3
# -*- coding: utf-8 -*-
"""
    :Author: yuangezhizao
    :Time: 2021/1/7 10:10
    :Site: https://www.yuangezhizao.cn
    :Copyright: © 2020~2021 yuangezhizao <root@yuangezhizao.cn>
"""
import datetime

import flask
from flask_login import login_user, logout_user, login_required, current_user

from device_manager.models.device import Device
from device_manager.models.user import User
from device_manager.plugins.send_email import send_transfer_email, send_confirm_email

app = flask.current_app
bp = flask.Blueprint('main', __name__)


@bp.route('/')
def site_index():
    # from device_manager.plugins.extensions import db
    # db.create_all()
    if current_user.is_authenticated:
        my_now_device_data = Device.query.filter_by(now_person=current_user).order_by(Device.id.asc()).all()
        my_next_device_data = Device.query.filter_by(next_person=current_user).order_by(Device.id.asc()).all()
        return flask.render_template('index.html', my_now_device_data=my_now_device_data,
                                     my_next_device_data=my_next_device_data)
    return flask.render_template('index.html')


@bp.route('/auth/index', methods=['GET', 'POST'])
def auth_index():
    if current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.site_index'))
    if flask.request.method == 'POST':
        username = flask.request.form.get('username')
        user = User.query.filter_by(username=username).first()
        if user is None:
            flask.flash('不存在的用户名！', 'negative')
        elif not user.validate_password(flask.request.form['password']):
            flask.flash('不正确的密码！', 'negative')
        else:
            remember = flask.request.form.get('remember', False)
            login_user(user, remember)
            return flask.redirect(flask.url_for('main.site_index'))
    return flask.render_template('auth/index.html')


@bp.route('/auth/change_passwd', methods=['GET', 'POST'])
@login_required
def auth_change_passwd():
    if flask.request.method == 'POST':
        password = flask.request.form.get('password')
        user = User.query.filter_by(username=current_user.username).first_or_404()
        user.password_hash = password
        user.save()
        flask.flash(f'修改密码为【{password}】成功！', 'brown')
        return flask.redirect(flask.url_for('main.site_index'))
    return flask.render_template('auth/change_passwd.html')


@bp.route('/auth/logout')
@login_required
def auth_logout():
    logout_user()
    flask.flash('注销成功！', 'info')
    return flask.redirect(flask.url_for('main.auth_index'))


@bp.route('/transfer/device', methods=['GET', 'POST'])
@login_required
def transfer_device():
    serial = flask.request.args.get('serial')
    transfer_device_data = Device.query.filter_by(serial=serial).first_or_404()
    if flask.request.method == 'POST':
        func = flask.request.form.get('func')
        if func == 'start_transfer':
            if transfer_device_data.now_person != current_user:
                return '这已经不是你的设备了'
            next_user_id = flask.request.form.get('next_user')
            next_user = User.query.filter_by(username=next_user_id).first_or_404()
            now_user = transfer_device_data.now_person
            # 邮件送信 CC 当前所有者
            transfer_device_data.next_person = next_user
            transfer_device_data.save()
            try:
                send_transfer_email(serial, next_user.email, now_user.email)
            except Exception as e:
                print(e)
            return flask.redirect(flask.url_for('main.transfer_device', serial=serial))
        elif func == 'stop_transfer':
            transfer_confirm = flask.request.form.get('transfer_confirm')
            if transfer_confirm:
                if transfer_device_data.next_person != current_user:
                    return '此设备并不需要你进行确认'
                next_user = transfer_device_data.next_person
                now_user = transfer_device_data.now_person
                # 邮件送信 CC 当前所有者
                transfer_device_data.now_person = next_user
                transfer_device_data.next_person = None
                transfer_device_data.save()
                try:
                    send_confirm_email(serial, now_user.email, next_user.email)
                except Exception as e:
                    print(e)
                if 'transfer' not in flask.request.referrer:
                    return flask.redirect(flask.url_for('main.site_index'))
                return flask.redirect(flask.url_for('main.transfer_device', serial=serial))
    user_all = User.query.order_by(User.id.asc()).all()
    device_offline_timedelta = datetime.timedelta(minutes=20)
    if transfer_device_data.device_online_time is not None:
        device_online_time_utc = transfer_device_data.device_online_time - datetime.timedelta(hours=8)
    else:
        device_online_time_utc = ''
    # 转换为 UTC 时间
    return flask.render_template('transfer/device.html', transfer_device_data=transfer_device_data, user_all=user_all,
                                 device_offline_timedelta=device_offline_timedelta,
                                 device_online_time_utc=device_online_time_utc)


@bp.route('/manage/index')
@login_required
def manage_index():
    manage_index_data = Device.query.order_by(Device.id.asc()).all()
    device_offline_timedelta = datetime.timedelta(minutes=20)
    for data in manage_index_data:
        if data.device_online_time is not None:
            data.device_online_time_utc = data.device_online_time - datetime.timedelta(hours=8)
    return flask.render_template('manage/index.html', device_offline_timedelta=device_offline_timedelta,
                                 manage_index_data=manage_index_data)


@bp.route('/report')
def report():
    serial = flask.request.args.get('serial')
    username = flask.request.args.get('user')
    fmt_serial = serial.zfill(6)
    device = Device.query.filter_by(serial=fmt_serial).first_or_404()
    device.device_online_time = datetime.datetime.now()
    try:
        name = User.query.filter_by(username=username).first().name
        device.backup_1 = name
    except Exception:
        print(f'用户 ID 为【{username}】的用户不存在')
    device.save()
    return f'序列号为【{fmt_serial}】的 CANoe 设备上次在线时间已更新'

src/device_manager/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="author" content="yuangezhizao"/>
    <meta name="Copyright" content="Copyright yuangezhizao All Rights Reserved."/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='/static/Semantic-UI-CSS-master/semantic.min.css') }}">
    <link rel="dns-prefetch" href="//lab.yuangezhizao.cn">
    <link rel="dns-prefetch" href="//www.yuangezhizao.cn">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=yes">
    {#    <script>#}
    {#        function getIEVersion() {#}
    {#            var e = 99;#}
    {#            if ("Microsoft Internet Explorer" === navigator.appName) {#}
    {#                var t = navigator.userAgent;#}
    {#                null != new RegExp("MSIE ([0-9]{1,}[.0-9]{0,})").exec(t) && (e = parseFloat(RegExp.$1))#}
    {#            }#}
    {#            return e#}
    {#        }#}
    {##}
    {#        getIEVersion() < 11 && window && (window.location.href = "{{ url_for('static', filename='/html/IE.html') }}")#}
    {#    </script>#}
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}
    <div class="ui container">
        <div class="ui blue pointing menu">
            {% block nav %}
                <a class="active item"><i class="home icon"></i>首页</a>
                <a class="item" href="{{ url_for('static', filename='/static/html/update.html') }}"><i
                        class="arrow up icon"></i>更新日志</a>
                <div class="right menu">
                    {% if current_user.is_authenticated %}
                        <a class="item" href="{{ url_for('main.auth_change_passwd') }}"><i class="key icon"></i>修改密码</a>
                        <a class="item" href="{{ url_for('main.auth_logout') }}"><i class="sign out icon"></i>注销</a>
                    {% else %}
                        <a class="up item" href="{{ url_for('main.auth_index') }}"><i class="sign in icon"></i>登录</a>
                    {% endif %}
                </div>
            {% endblock %}
        </div>
        {% block content %}{% endblock %}
        <div class="ui divider"></div>
        <footer>
            <div class="ui info message" style="text-align: center;">
                ALSI&nbsp&nbsp&nbsp&nbsp©&nbsp&nbsp&nbsp&nbsp2021
            </div>
        </footer>
    </div>
{% endblock %}
<script src="{{ url_for('static', filename='/static/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='/static/Semantic-UI-CSS-master/semantic.min.js') }}"></script>
<script>
    $('.message .close').on('click', function () {
        $(this).closest('.message').transition('fade');
    });
    $('.selection.dropdown').dropdown();
    console.log('没错，控制台彩蛋（');
    console.warn('小伙子你不要搞事情');
    console.warn('Copyright © 2021 yuangezhizao');
</script>
{% block script %}{% endblock %}
{{ moment.include_moment(local_js=url_for('static', filename='static/js/moment-with-locales.min.js')) }}
{{ moment.locale(language='zh-CN') }}
</body>
</html>

src/device_manager/templates/index.html
{% extends "/base.html" %}

{% from 'macros.html' import message_part with context %}

{% block title %}ALSI ES CANoe 设备管理系统{% endblock %}

{% block content %}
    <div class="ui positive message">
        <h2 class="ui header">欢迎访问 ヽ(･ω･´ﾒ)</h2>
        <p>ALSI ES CANoe 设备管理系统</p>
    </div>

    {{ message_part() }}

    {% if current_user.is_authenticated %}
        <h4 class="ui top attached block blue header">
            我的
        </h4>
        <div class="ui bottom attached blue segment">
            你好，<b>{{ current_user.name }}</b>
            <br>
            {% if my_now_device_data %}
                <br>
                ① 以下是你拥有的设备：
                <br>
                <br>
                {% for my_now_device in my_now_device_data %}
                    <a class="ui mini green button"
                       href="{{ url_for('main.transfer_device') }}?serial={{ my_now_device.serial }}">{{ my_now_device.serial }}</a>
                {% endfor %}
            {% else %}
                <br>
                ① 你暂无拥有的设备
            {% endif %}
            <br>
            {% if my_next_device_data %}
                <br>
                ② 以下是你需要确认的设备：
                <table class="ui very compact collapsing table">
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>设备序列号</th>
                        <th>设备来自</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for my_next_device in my_next_device_data %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td><a class="ui mini blue button"
                                   href="{{ url_for('main.transfer_device') }}?serial={{ my_next_device.serial }}">
                                {{ my_next_device.serial }}</a></td>
                            <td>{{ my_next_device.now_person }}</td>
                            <td>{% if my_next_device.device_available_status == 0 %}
                                <form class="ui inline" method="post"
                                      action="{{ url_for('main.transfer_device') }}?serial={{ my_next_device.serial }}">
                                    <input name="func" value="stop_transfer" type="hidden">
                                    <button class="ui animated fade positive mini button" name="transfer_confirm"
                                            value="1">
                                        <div class="visible content">确认接收{{ my_next_device.serial }}</div>
                                        <div class="hidden content">
                                            <i class="check circle outline icon"></i>
                                        </div>
                                    </button>
                                </form>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    {% else %}
        <div class="ui yellow message">
            <i class="close icon"></i>
            <div class="header">警告
            </div>
            未登录用户，
            <a class="item" href="{{ url_for('main.auth_index') }}"><i class="sign in icon"></i>点此登录</a>
        </div>
    {% endif %}

    <h4 class="ui top attached block brown header">
        管理
    </h4>
    <div class="ui bottom attached brown segment">
        <a href="{{ url_for('main.manage_index') }}">全部设备</a>
        {% if current_user.username in ('ASDL1B1DL033', 'ASDL1B8DL002', 'ASDL1B8DL003', 'ASDL1B5DL037', 'ASDL1B8DL069') %}
            <br>
            <br>
            <a class='ui red' href="/admin">【Admin】数据库管理</a>
        {% endif %}
    </div>
{% endblock %}

src/device_manager/templates/macros.html
{% macro message_part() %}
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <div class="ui {{ messages[0][0] }} message">
                <i class="close icon"></i>
                <div class="header">
                </div>
                {{ messages[0][1] }}
            </div>
        {% endif %}
    {% endwith %}
{% endmacro %}